name: snowchecked
version: 0.0.0.1
github: robertfischer/hs-snowflake-checked
license: Apache-2.0
author: Robert Fischer
maintainer: smokejumperit@gmail.com
copyright: 2021 Robert Fischer

extra-source-files:
  - LICENSE
  - README.md
  - package.yaml
  - stack.yaml

# Metadata used when publishing your package
synopsis: Short description of your package
category: Data

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see ./README.md

dependencies:
  - base
  - bytestring
  - wide-word
  - data-default
  - extra
  - time
  - deepseq

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Werror=unused-do-bind
  - -Werror=incomplete-record-updates
  - -Werror=incomplete-uni-patterns
  - -Werror=partial-fields
  - -Werror=incomplete-patterns
  - -Wredundant-constraints
  - -Werror=missing-exported-signatures
  - -Wmissed-specializations
  - -Wno-unused-packages
  - -Wunused-type-patterns
  - -Werror=warnings-deprecations
  - -Wnoncanonical-monad-instances
  - -Wno-type-defaults
  - -feager-blackholing
  - -fexcess-precision
  - -flate-dmd-anal
  - -fmax-inline-alloc-size=1024
  - -fmax-simplifier-iterations=8
  - -fpedantic-bottoms
  - -fregs-iterative
  - -fsimplifier-phases=4
  - -fspec-constr-count=10
  - -fspecialise-aggressively
  - -flate-specialise
  - -fstatic-argument-transformation
  - -fstrictness-before=3

library:
  source-dirs: src

tests:
  test-suite:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - snowchecked
      - hspec

    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
